# Generated by Django 4.0.4 on 2022-05-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj2Cmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obj', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai1', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai2', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai3', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai4', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai5', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai6', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai7', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai8', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai9', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai10', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obj2Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datain', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimean', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('statmin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('statmax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('mlmin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('mlmax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('err', models.CharField(choices=[('0', 'Система в норме'), ('1', 'Аварийная нижняя граница'), ('2', 'Предупредительная нижняя граница'), ('3', 'Предупредительная верхняя граница'), ('4', 'Аварийная верхняя граница')], max_length=7)),
                ('sts', models.CharField(choices=[('0', 'Система в норме'), ('1', 'Не подтвержден'), ('2', 'Подтвержден')], max_length=7)),
                ('dataout', models.DateTimeField()),
                ('datacheck', models.DateTimeField()),
                ('cmnt', models.CharField(max_length=50)),
                ('id_ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sensor')),
                ('id_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects')),
            ],
        ),
        migrations.CreateModel(
            name='Obj1Cmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai1', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai2', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai3', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai4', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai5', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai6', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai7', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai8', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai9', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('ai10', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('id_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects')),
            ],
        ),
        migrations.CreateModel(
            name='Obj1Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('datain', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimean', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('aimin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('statmin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('statmax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('mlmin', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('mlmax', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('err', models.CharField(choices=[('0', 'Система в норме'), ('1', 'Аварийная нижняя граница'), ('2', 'Предупредительная нижняя граница'), ('3', 'Предупредительная верхняя граница'), ('4', 'Аварийная верхняя граница')], max_length=7)),
                ('sts', models.CharField(choices=[('0', 'Система в норме'), ('1', 'Не подтвержден'), ('2', 'Подтвержден')], max_length=7)),
                ('dataout', models.DateTimeField()),
                ('datacheck', models.DateTimeField()),
                ('cmnt', models.CharField(max_length=50)),
                ('id_ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sensor')),
            ],
        ),
    ]
