# Generated by Django 4.0.4 on 2022-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj1Ai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_obj', models.IntegerField()),
                ('id_ai', models.IntegerField()),
                ('datain', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimean', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('statmin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('statmax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mlmin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mlmax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('err', models.IntegerField()),
                ('sts', models.IntegerField()),
                ('dataout', models.DateTimeField()),
                ('datacheck', models.DateTimeField()),
                ('cmnt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obj1Cmn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_obj', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai1', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai2', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai3', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai4', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai5', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai6', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai7', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai8', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai9', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai10', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Obj2Ai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_obj', models.IntegerField()),
                ('id_ai', models.IntegerField()),
                ('datain', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimean', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aimin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('statmin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('statmax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mlmin', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mlmax', models.DecimalField(decimal_places=6, max_digits=9)),
                ('err', models.IntegerField()),
                ('sts', models.IntegerField()),
                ('dataout', models.DateTimeField()),
                ('datacheck', models.DateTimeField()),
                ('cmnt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obj2Cmn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_obj', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('mode', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai1', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai2', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai3', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai4', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai5', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai6', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai7', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai8', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai9', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ai10', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
