# Generated by Django 4.0.4 on 2022-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj1ai',
            name='cmnt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='cmnt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
