# Generated by Django 4.0.4 on 2022-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_obj1ai_cmnt_alter_obj2ai_cmnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj2ai',
            name='cmnt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
