# Generated by Django 4.0.4 on 2022-05-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_obj1ai_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj1cmn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
