# Generated by Django 4.0.4 on 2022-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_obj1cmn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj1ai',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
