# Generated by Django 4.0.4 on 2022-05-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_obj2ai_cmnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai1',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai10',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai3',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai4',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai5',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai6',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai7',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai8',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai9',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects'),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='mode',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
