# Generated by Django 4.0.4 on 2022-05-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_obj1ai_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj1ai',
            name='err',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='sts',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='err',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='sts',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
