# Generated by Django 4.0.4 on 2022-05-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_obj1ai_err'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='sts',
            field=models.CharField(choices=[('0', 'Система в норме'), ('1', 'Не подтвержден'), ('2', 'Подтвержден')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='id_ai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sensor'),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects'),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects'),
        ),
    ]
