# Generated by Django 4.0.4 on 2022-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_obj2cmn_ai1_alter_obj2cmn_ai10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obj2ai',
            name='id_obj',
        ),
        migrations.AddField(
            model_name='obj2ai',
            name='data',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='cmnt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
