# Generated by Django 4.0.4 on 2022-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_objects_sensor_alter_obj1ai_sts_alter_obj1ai_id_ai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj1cmn',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='aimax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='aimean',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='aimin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='mlmax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='mlmin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='mode',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='statmax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1ai',
            name='statmin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai1',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai10',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai2',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai3',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai4',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai5',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai6',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai7',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai8',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='ai9',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj1cmn',
            name='mode',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
