# Generated by Django 4.0.4 on 2022-05-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_rename_data_obj1cmn_date_alter_obj1ai_aimax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj2cmn',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='aimax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='aimean',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='aimin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='err',
            field=models.CharField(choices=[('0', 'Система в норме'), ('1', 'Аварийная нижняя граница'), ('2', 'Предупредительная нижняя граница'), ('3', 'Предупредительная верхняя граница'), ('4', 'Аварийная верхняя граница')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='id_ai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.sensor'),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects'),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='mlmax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='mlmin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='mode',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='statmax',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='statmin',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2ai',
            name='sts',
            field=models.CharField(choices=[('0', 'Система в норме'), ('1', 'Не подтвержден'), ('2', 'Подтвержден')], max_length=7),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai1',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai10',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai2',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai3',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai4',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai5',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai6',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai7',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai8',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='ai9',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objects'),
        ),
        migrations.AlterField(
            model_name='obj2cmn',
            name='mode',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
