# Generated by Django 4.0.4 on 2022-05-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_rename_data_obj2cmn_date_alter_obj2ai_aimax_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objects',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
    ]
